// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using System;
using Newtonsoft.Json;

namespace Perb.FlightPlanning.Shared.Domains.Write.ValueObject.Solver.Response
{
    /// <summary>
    /// PlannedFlight
    /// </summary>
    public class PlannedFlightResponse
    {

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "aircraftContract")]
        public AircraftContractResponse AircraftContract { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'SUNDAY', 'MONDAY',
        /// 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY'
        /// </summary>
        [JsonProperty(PropertyName = "dayOfWeek")]
        public DayOfWeek DayOfWeek { get; set; }


        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "end")]
        public int End { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "marineUnit")]
        public MarineUnitResponse MarineUnit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "seats")]
        public int? Seats { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "start")]
        public int Start { get; set; }


    }
}
