// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using Newtonsoft.Json;

namespace Perb.FlightPlanning.Shared.Domains.Write.ValueObject.Solver.Response
{
    /// <summary>
    /// Score
    /// </summary>
    public class ScoreResponse
    {
       

      

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hard")]
        public long Hard { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "medium")]
        public long Medium { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "soft")]
        public long Soft { get; set; }

    }
}
