// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using Newtonsoft.Json;

namespace Perb.FlightPlanning.Shared.Domains.Write.ValueObject.Solver.Request
{
    /// <summary>
    /// FlightPreference
    /// </summary>
    public class FlightPreferenceRequest
    {
       

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "marineUnit")]
        public MarineUnitRequest MarineUnitRequest { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "period")]
        public PeriodRequest PeriodRequest { get; set; }

    }
}
