// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using Newtonsoft.Json;

namespace Perb.FlightPlanning.Shared.Domains.Write.ValueObject.Solver.Request
{
    /// <summary>
    /// Period
    /// </summary>
    public class PeriodRequest
    {
      

        /// <summary>
        /// Gets or sets possible values include: 'SUNDAY', 'MONDAY',
        /// 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY'
        /// </summary>
        [JsonProperty(PropertyName = "dayOfWeek")]
        public string DayOfWeek { get; set; }


        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "end")]
        public int? End { get; set; }


        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "start")]
        public int? Start { get; set; }


    }
}
