// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace Perb.FlightPlanning.Shared.Domains.Write.ValueObject.Solver.Request
{
    /// <summary>
    /// PlanFlightsCommand
    /// </summary>
    public class PlanFlightsRequest
    {   
        [JsonProperty(PropertyName = "clientConnectionId")]
        public string ClientConnectionId { get; set; }

        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        [JsonProperty(PropertyName = "planningId")]
        public Guid PlanningId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "aircraftContracts")]
        public IList<AircraftContractRequest> AircraftContracts { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "daysOfWeek")]
        public IList<string> DaysOfWeek { get; set; }

        [JsonProperty(PropertyName = "solutionScoreChangedSubscribed")]
        public bool SolutionScoreChangedSubscribed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "debugEnabled")]
        public bool? DebugEnabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firstDepartureMustBeAtInMinutes")]
        public int? FirstDepartureMustBeAtInMinutes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "intervalBetweenFlightsInMinutes")]
        public int? IntervalBetweenFlightsInMinutes { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'LANDING_AT_THE_AIRPORT',
        /// 'TAKE_OFF_FROM_MARINE_UNIT'
        /// </summary>
        [JsonProperty(PropertyName = "lastFlightValidationType")]
        public string LastFlightValidationType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastLandingMustBeUntilInMinutes")]
        public int? LastLandingMustBeUntilInMinutes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lowerLimit")]
        public int? LowerLimit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "marineUnits")]
        public IList<MarineUnitRequest> MarineUnits { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "runBenchmark")]
        public bool? RunBenchmark { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timeAtMarineUnit")]
        public IList<TimeAtMarineUnitRequest> TimeAtMarineUnit { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "upperLimit")]
        public int? UpperLimit { get; set; }

    }
}
