// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

using Newtonsoft.Json;

namespace Perb.FlightPlanning.Shared.Domains.Write.ValueObject.Solver.Request
{
    /// <summary>
    /// TimeAtMarineUnit
    /// </summary>
    public class TimeAtMarineUnitRequest
    {
        public TimeAtMarineUnitRequest(string aircraftContractType, int? timeInMinutes)
        {
            AircraftContractType = aircraftContractType;
            TimeInMinutes = timeInMinutes;
        }
        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "aircraftContractType")]
        public string AircraftContractType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timeInMinutes")]
        public int? TimeInMinutes { get; set; }

    }
}
